ApiKey:                 # API Key
ApiSecret:              # API秘钥
ApiPassphrase:          # API密码
Debug: false            # 调试模式
Simulate: true          # 模拟交易
CexName: "okex"         # 交易所名称(okex/binance...)s
Symbol: "PEPE-USDT"     # 交易对
CheckDur: "30s"         # 价格检查时间
Continuous: 5           # 价格持续上涨次数
TickerDur: "5s"         # 市场价更新时间
OrderDur: "15m"         # 订单下单时间间隔
Leverage: 10            # 杠杆倍数
FastRise: 0.001         # 暴涨比例
RiseThreshold: 0.015    # 涨幅触发阈值
StopLossPct: 0.01       # 止损百分比
PullBackRate: 0.018     # 价格回调比例
TradeAmountRate: 0.5    # 交易金额比例（余额百分比）


