# API Key
ApiKey:
# API秘钥
ApiSecret:
# API密码
ApiPassphrase:
# 调试模式
Debug: false
# 模拟交易
Simulate: false
# 交易所名称(okex/binance...)
CexName: "okex"
# 交易对
Symbol: "PEPE-USDT"
# 价格检查时间
CheckDur: "20s"
# 价格暴涨比例
FastRise: 0.001
# 价格持续暴涨次数
Continuous: 4
# 杠杆倍数
Leverage: 5
# 暴涨暴跌幅度
RiseThreshold: 0.015
# 止损百分比
StopLossPct: 0.2
# 价格回调比例（满足则平仓）
PullBackRate: 0.02
# 交易金额比例（余额百分比）
TradeAmountRate: 0.6


