
ApiKey:
ApiSecret:
ApiPassphrase:
CexName: "okex"
Market:
  PriceFlat: 0.001  # 正负范围内视为持平
  SlowRise: 0.002   # 慢涨
  FastRise: 0.003   # 暴涨

Contract:
  Symbol: "PEPE-USDT"     # 交易对
  PullBackRate: 0.015     # 价格回调比例
  TradeAmountRate: 0.3    # 交易金额比例（余额百分比）
  LeverMultiple: 3        # 杠杆倍数
  TickerInterval: "10s"   # 市场价监控时间间隔
  OrderInterval: "15m"    # 订单下单时间间隔
  ClosePosInterval: "10m" # 订单下单后多长时间内不允许平仓


